### PR TITLE
Rewrite the existing SauceLabs/Nightwatch Browser Test to Cypress and…

### PR DESCRIPTION
**Pull request by bereket-WMDE**
Bug: [T273775](https://phabricator.wikimedia.org/T273775)

### CODE REVIEW

**Review by micgro42 — CHANGES_REQUESTED** [review]
I think there is a bit more here that needs cleaning up:
* the old e2e tests and directory still exist in the `tests/` directory, the package.json still has the commands to run those tests. It also still has dependencies for nightwatch and saucelabs, those need to be uninstalled in a way that also removes them from the package-lock.json

**Comment by bereket-WMDE** [comment]
> I think there is a bit more here that needs cleaning up:
> 
>     * the old e2e tests and directory still exist in the `tests/` directory, the package.json still has the commands to run those tests. It also still has dependencies for nightwatch and saucelabs, those need to be uninstalled in a way that also removes them from the package-lock.json

@micgro42 updated. I also deleted some more unnecessary stuff and deleted the sauclabs tokens from github secrets

**Comment by micgro42** [comment]
There is still a nightwatch.conf.js. But after that is removed, then I think this is good to go

**Comment by bereket-WMDE** [comment]
> There is still a nightwatch.conf.js. But after that is removed, then I think this is good to go

deleted

**Comment by micgro42** [comment]
I noticed `tests_output/QueryBuilder.test.xml` just now. It would seem that was added in error, or was that intentional?

**Comment by bereket-WMDE** [comment]
> I noticed `tests_output/QueryBuilder.test.xml` just now. It would seem that was added in error, or was that intentional?

Yes, good catch. It was added in Error. I removed it now

**Review by micgro42 — APPROVED** [review]
\o/

**Pull request merged**
