### PR TITLE
Swap the condition if it's negate only

### PR DESCRIPTION
**Pull request by Ladsgroup**
Otherwise, it can't find anything.

### CODE REVIEW

**Comment by micgro42** [comment]
We can ignore Sonar on this PR - it is from an old configuration.

But I'm confused why this PR is needed at all. With the QB on the tests-system I can find results just fine with only a single without clause?

**Comment by Ladsgroup** [comment]
It happens in a rather specific case.
image

(Reported by Guergana)

The resulting query is https://w.wiki/w5z
Swap it and it'll works.

**Comment by micgro42** [comment]
Mh, the problem seems to be the labels. Without the labels it works just fine for me:

image
https://w.wiki/wZb

With labels it reliably times out, even if I set the limit to 2. Does it actually work for you with labels?

**Comment by Ladsgroup** [comment]
Yeah but the thing is that without the patch it gives "no result" which is semantically incorrect, while timeout is an operational issue (e.g. I hope it'll get better with the search team addressing some issues.)

**Review by micgro42 — APPROVED** [review]
Oh well. I'll create a ticket to figure out why the labels always time out.

**Pull request merged**
