### PR TITLE
feat: rebuild Query Builder from URL param

### PR DESCRIPTION
**Pull request by Ladsgroup**
Todo:
- [x] refactor code in App.vue and add tests for it

### CODE REVIEW

**Comment by micgro42** [comment]
To test this out, add the following Button locally to the template of `QueryBuilder.vue`:
```vue
				<Button
					variant="quiet"
					type="progressive"
					@click.native="getLink"
				>
					Link to query builder
				</Button>
```

and the following method to its methods section:

```ts
		getLink(): void {
			const querySerializer = new QuerySerializer();
			const serializedQuery = querySerializer.serialize( this.$store.state );
			location = 'http://localhost:8080/?query=' + serializedQuery;
		},
```

**Comment by micgro42** [comment]
This code is ready for review with the notable exception of the code in App.vue and its missing test.

I would be happy about feedback on the rest of it :)

**Comment by micgro42** [comment]
Can now be easily tested with the permalink in the footer 😗🎶

**Review by Ladsgroup — COMMENTED** [review]
I can't officially approve it as I started the PR but I approve it (since Michael did most of the work). It looks good. It's slightly large but it's mostly tests. Also tested locally and works just fine. We should move it out of footer soonish ^^

**Review by micgro42 — APPROVED** [review]
> I can't officially approve it as I started the PR but I approve it (since Michael did most of the work). It looks good. It's slightly large but it's mostly tests. Also tested locally and works just fine. We should move it out of footer soonish ^^


Approving it formally on @Ladsgroup's stead.

**Pull request merged**
