### PR TITLE
Add negate mode to buildQuery

### PR DESCRIPTION
**Pull request by Ladsgroup**
Bug: T272012

### CODE REVIEW

**Review by micgro42 — CHANGES_REQUESTED** [review]
No, this is not working. https://w.wiki/uTe is not finding all items without the postal code 10777.

If there are no other conditions, then it needs the line `?item wikibase:sitelinks [].` first to select all items.

**Comment by guergana** [comment]
> No, this is not working. https://w.wiki/uTe is not finding all items without the postal code 10777.
> 
> If there are no other conditions, then it needs the line `?item wikibase:sitelinks [].` first to select all items.

I like that "No" at the beginning of the sentence for emphasis. :smile:

**Comment by Ladsgroup** [comment]
> wikibase:sitelinks

I'm trying to make this happen, it's just I don't know how to write it in a way sparqljs would understand. Working on it.

**Comment by Ladsgroup** [comment]
> sitelinks

Done now. Tested and it works fine even for items that don't have a sitelink.

**Comment by micgro42** [comment]
> > sitelinks
> 
> Done now. Tested and it works fine even for items that don't have a sitelink.

Awesome!

**Review by micgro42 — APPROVED** [review]

**Pull request merged**
